"use client";

import { useState, useEffect } from "react";
import { usePrivy } from "@privy-io/react-auth";
import { X, CreditCard, Wallet, Settings, User, Key } from "lucide-react";
import { QRCodeSVG } from "qrcode.react";

interface SettingsModalProps {
  isOpen: boolean;
  onClose: () => void;
}

type SettingsTab = "account" | "credits" | "wallet";

export default function SettingsModal({ isOpen, onClose }: SettingsModalProps) {
  const { authenticated, ready, user: privyUser, getAccessToken } = usePrivy();
  const [activeTab, setActiveTab] = useState<SettingsTab>("credits");
  const [balance, setBalance] = useState<any>(null);
  const [loading, setLoading] = useState(false);
  const [balanceLoading, setBalanceLoading] = useState(false);
  const [balanceError, setBalanceError] = useState<string | null>(null);
  const [paymentIntent, setPaymentIntent] = useState<any>(null);
  const [showImportWallet, setShowImportWallet] = useState(false);
  const [showExportWallet, setShowExportWallet] = useState(false);
  const [privateKey, setPrivateKey] = useState("");
  const [importing, setImporting] = useState(false);
  const [importError, setImportError] = useState<string | null>(null);
  const [exportedKey, setExportedKey] = useState<any>(null);
  const [exporting, setExporting] = useState(false);
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    // Only fetch balance when Privy is ready and user is authenticated
    if (isOpen && ready && authenticated) {
      // Add a small delay to ensure Privy is fully initialized
      const timer = setTimeout(() => {
        fetchBalance();
      }, 200);
      return () => clearTimeout(timer);
    }
  }, [isOpen, ready, authenticated]);

  const fetchBalance = async (retryCount = 0) => {
    // Don't proceed if Privy isn't ready
    if (!ready || !authenticated) {
      console.log("[SettingsModal] Privy not ready:", { ready, authenticated });
      setBalanceError("Waiting for authentication...");
      return;
    }

    setBalanceLoading(true);
    setBalanceError(null);

    try {
      // Wait a bit for Privy to be fully ready
      await new Promise(resolve => setTimeout(resolve, 300));
      
      const token = await getAccessToken();
      console.log("[SettingsModal] Token retrieved:", token ? "Yes" : "No", token?.substring(0, 20) + "...");
      console.log("[SettingsModal] Token type:", typeof token, "Token length:", token?.length);
      
      if (!token) {
        console.warn("[SettingsModal] No access token available");
        setBalanceError("No access token. Please log in again.");
        setBalanceLoading(false);
        
        // Retry once after a delay
        if (retryCount === 0) {
          setTimeout(() => fetchBalance(1), 1000);
        }
        return;
      }

      // Ensure token is a string and clean it
      let cleanToken: string;
      
      if (typeof token === 'string') {
        cleanToken = token.trim();
      } else if (token && typeof token === 'object' && 'toString' in token) {
        // Handle edge cases where token might be an object
        cleanToken = String(token).trim();
      } else {
        cleanToken = String(token || '').trim();
      }
      
      if (!cleanToken || cleanToken.length === 0) {
        console.error("[SettingsModal] Token is empty after cleaning");
        setBalanceError("Invalid token format.");
        setBalanceLoading(false);
        return;
      }

      // Validate JWT format (should have 3 parts separated by dots)
      const jwtParts = cleanToken.split('.');
      if (jwtParts.length !== 3) {
        console.error("[SettingsModal] Token does not appear to be a valid JWT");
        console.error("[SettingsModal] Token parts count:", jwtParts.length);
        setBalanceError("Invalid token format - expected JWT.");
        setBalanceLoading(false);
        return;
      }

      console.log("[SettingsModal] Token validated - JWT format OK, length:", cleanToken.length);
      console.log("[SettingsModal] Fetching balance with cleaned token");
      const res = await fetch("/api/payments/balance", {
        method: 'GET',
        headers: { 
          Authorization: `Bearer ${cleanToken}`,
          'Content-Type': 'application/json',
        },
      });
      
      console.log("[SettingsModal] Balance API response:", res.status);
      
      if (res.ok) {
        const data = await res.json();
        console.log("[SettingsModal] Balance data received:", { 
          hasDepositWallet: !!data.depositWallet,
          depositWallet: data.depositWallet 
        });
        setBalance(data);
        setBalanceError(null);
        
        // Deposit wallet is now auto-generated by the balance endpoint
        if (data.depositWallet) {
          console.log("[SettingsModal] Deposit wallet:", data.depositWallet);
        } else {
          console.warn("[SettingsModal] Deposit wallet not found - check server logs");
          setBalanceError("Deposit wallet generation failed. Please refresh the page.");
        }
      } else {
        const errorData = await res.json().catch(() => ({}));
        console.error("[SettingsModal] Failed to fetch balance:", res.status, errorData);
        
        // If 401, the token might be invalid - try to refresh
        if (res.status === 401) {
          const errorMsg = errorData.error || "Unauthorized";
          const details = errorData.details || "";
          console.warn("[SettingsModal] Unauthorized:", errorMsg, details);
          
          let errorMessage = `Authentication failed: ${errorMsg}`;
          if (details) {
            errorMessage += `\n\nDetails: ${details}`;
          }
          
          // Check if it's a Privy configuration issue
          if (details?.includes('Privy not configured') || details?.includes('Privy verification failed')) {
            errorMessage += "\n\nPlease check:\n1. PRIVY_APP_SECRET is set in Doppler\n2. PRIVY_APP_SECRET matches your Privy dashboard\n3. Restart your dev server after setting the secret";
          } else {
            errorMessage += "\n\nPlease try logging out and back in.";
          }
          
          setBalanceError(errorMessage);
          
          // Retry once after a delay if first attempt
          if (retryCount === 0) {
            setTimeout(() => fetchBalance(1), 2000);
            return;
          }
        } else if (res.status === 404) {
          // User not found - might need to be created
          const errorMsg = errorData.error || "User not found";
          const hint = errorData.hint || "";
          console.warn("[SettingsModal] User not found:", errorMsg, hint);
          setBalanceError(`User not found in database. ${hint || 'Please try logging out and back in to create your account.'}`);
        } else {
          setBalanceError(`Failed to load balance: ${errorData.error || res.statusText}`);
        }
      }
    } catch (e: any) {
      console.error("[SettingsModal] Error fetching balance:", e);
      setBalanceError(`Network error: ${e?.message || 'Failed to fetch balance'}`);
      
      // Retry once after a delay if first attempt
      if (retryCount === 0) {
        setTimeout(() => fetchBalance(1), 2000);
        return;
      }
    } finally {
      setBalanceLoading(false);
    }
  };

  const handleCreatePaymentIntent = async (tokenSymbol: string = "SOL") => {
    if (!balance || balance.canCreateFreeProject) return;
    if (!ready || !authenticated) {
      console.warn("Privy not ready, cannot create payment intent");
      return;
    }
    
    setLoading(true);
    try {
      const token = await getAccessToken();
      if (!token) {
        console.warn("No access token available");
        setLoading(false);
        return;
      }
      const res = await fetch("/api/payments/create-intent", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${token}`,
        },
        body: JSON.stringify({ tokenSymbol }),
      });

      if (res.ok) {
        const data = await res.json();
        if (data.freeProject) {
          alert("Your first project is free!");
          return;
        }
        setPaymentIntent(data.intent);
        
        // Start polling for payment confirmation
        if (data.intent?.id) {
          pollPaymentStatus(data.intent.id);
        }
      }
    } catch (e) {
      console.error("Error creating payment intent:", e);
    } finally {
      setLoading(false);
    }
  };

  const pollPaymentStatus = async (intentId: string) => {
    const maxAttempts = 30; // Poll for up to 5 minutes (30 * 10s)
    let attempts = 0;
    
    const poll = async () => {
      if (attempts >= maxAttempts) {
        console.log("Payment polling timeout");
        return;
      }
      
      // Don't poll if Privy isn't ready
      if (!ready || !authenticated) {
        console.warn("Privy not ready, skipping poll");
        return;
      }
      
      try {
        const token = await getAccessToken();
        if (!token) {
          console.warn("No access token available for polling");
          return;
        }
        const res = await fetch("/api/payments/poll", {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            Authorization: `Bearer ${token}`,
          },
          body: JSON.stringify({ intentId }),
        });
        
        if (res.ok) {
          const data = await res.json();
          if (data.status === "confirmed") {
            // Payment confirmed!
            setPaymentIntent(null);
            await fetchBalance(); // Refresh balance
            alert("Payment confirmed! You can now create your project.");
            return;
          } else if (data.status === "pending") {
            // Continue polling
            attempts++;
            setTimeout(poll, 10000); // Poll every 10 seconds
          }
        }
      } catch (e) {
        console.error("Error polling payment:", e);
        attempts++;
        setTimeout(poll, 10000);
      }
    };
    
    poll();
  };

  const handleImportUserWallet = async () => {
    if (!privateKey.trim()) {
      setImportError('Please enter a private key');
      return;
    }
    if (!ready || !authenticated) {
      setImportError('Please wait for authentication to complete');
      setImporting(false);
      return;
    }

    setImporting(true);
    setImportError(null);

    try {
      const token = await getAccessToken();
      if (!token) {
        setImportError('No access token available');
        setImporting(false);
        return;
      }
      const res = await fetch("/api/wallet/import", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${token}`,
        },
        body: JSON.stringify({ privateKey: privateKey.trim() }),
      });

      const data = await res.json();

      if (!res.ok) {
        setImportError(data.error || 'Failed to import wallet');
        return;
      }

      // Success - refresh and close
      setPrivateKey("");
      setShowImportWallet(false);
      setImportError(null);
      alert('Wallet imported successfully!');
      // Refresh page to show updated wallet
      window.location.reload();
    } catch (e: any) {
      console.error("Error importing wallet:", e);
      setImportError(e?.message || 'Failed to import wallet');
    } finally {
      setImporting(false);
    }
  };

  const handleExportUserWallet = async () => {
    if (!ready || !authenticated) {
      alert('Please wait for authentication to complete');
      return;
    }
    
    setExporting(true);
    try {
      const token = await getAccessToken();
      if (!token) {
        alert('No access token available');
        setExporting(false);
        return;
      }
      const res = await fetch("/api/wallet/export", {
        headers: { Authorization: `Bearer ${token}` },
      });

      const data = await res.json();

      if (!res.ok) {
        alert(data.error || 'Failed to export wallet');
        return;
      }

      setExportedKey(data);
      setShowExportWallet(true);
    } catch (e: any) {
      console.error("Error exporting wallet:", e);
      alert('Failed to export wallet');
    } finally {
      setExporting(false);
    }
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-sm">
      <div className="relative w-full max-w-6xl h-[90vh] bg-gray-900 rounded-2xl border border-gray-800 shadow-2xl flex overflow-hidden">
        {/* Close button */}
        <button
          onClick={onClose}
          className="absolute top-4 right-4 z-10 p-2 text-gray-400 hover:text-white transition-colors"
        >
          <X className="w-5 h-5" />
        </button>

        {/* Left Sidebar */}
        <div className="w-64 bg-gray-950 border-r border-gray-800 p-6 flex flex-col">
          <div className="mb-8">
            <h2 className="text-xl font-bold text-white mb-2">Settings</h2>
            <p className="text-gray-400 text-sm">Manage your account</p>
          </div>

          <nav className="flex-1 space-y-1">
            <button
              onClick={() => setActiveTab("credits")}
              className={`w-full flex items-center gap-3 px-4 py-3 rounded-lg text-left transition-colors ${
                activeTab === "credits"
                  ? "bg-cyan-500/20 text-cyan-300 border border-cyan-500/30"
                  : "text-gray-400 hover:text-white hover:bg-gray-800/50"
              }`}
            >
              <CreditCard className="w-5 h-5" />
              <span>Credits & Billing</span>
            </button>

            <button
              onClick={() => setActiveTab("wallet")}
              className={`w-full flex items-center gap-3 px-4 py-3 rounded-lg text-left transition-colors ${
                activeTab === "wallet"
                  ? "bg-cyan-500/20 text-cyan-300 border border-cyan-500/30"
                  : "text-gray-400 hover:text-white hover:bg-gray-800/50"
              }`}
            >
              <Wallet className="w-5 h-5" />
              <span>Wallet</span>
            </button>

            <button
              onClick={() => setActiveTab("account")}
              className={`w-full flex items-center gap-3 px-4 py-3 rounded-lg text-left transition-colors ${
                activeTab === "account"
                  ? "bg-cyan-500/20 text-cyan-300 border border-cyan-500/30"
                  : "text-gray-400 hover:text-white hover:bg-gray-800/50"
              }`}
            >
              <User className="w-5 h-5" />
              <span>Account</span>
            </button>
          </nav>
        </div>

        {/* Main Content */}
        <div className="flex-1 overflow-y-auto p-8">
          {activeTab === "credits" && (
            <div className="max-w-3xl">
              <h1 className="text-3xl font-bold text-white mb-2">Credits & Billing</h1>
              <p className="text-gray-400 mb-8">
                Manage your credits and payment methods. Your first 3 projects are free!
              </p>

              {/* Credit Balance Card */}
              <div className="bg-gradient-to-br from-gray-800/50 to-gray-900/50 rounded-2xl border border-gray-700 p-6 mb-6">
                <div className="flex items-center justify-between mb-4">
                  <div>
                    <h3 className="text-lg font-semibold text-white mb-1">Credit Balance</h3>
                    <p className="text-gray-400 text-sm">Available credits for projects</p>
                  </div>
                  <div className="text-right">
                    <div className="text-4xl font-bold text-cyan-400 mb-1">
                      {balance?.credits || 0}
                    </div>
                    <p className="text-gray-500 text-sm">credits</p>
                  </div>
                </div>

                {balance?.canCreateFreeProject && (
                  <div className="mt-4 p-3 bg-green-500/10 border border-green-500/30 rounded-lg">
                    <p className="text-green-300 text-sm">
                      ✓ Your first 3 projects are free! Create a project to get started.
                    </p>
                  </div>
                )}

                {balance && !balance.canCreateFreeProject && (
                  <div className="mt-4 p-3 bg-blue-500/10 border border-blue-500/30 rounded-lg">
                    <p className="text-blue-300 text-sm">
                      Next project: ${balance.nextProjectPrice.usd.toFixed(2)} USD
                      {balance.nextProjectPrice.hasDiscount && (
                        <span className="ml-2 text-green-300">(Blockmind token discount applied)</span>
                      )}
                    </p>
                  </div>
                )}
              </div>

              {/* Blockmind Token Status */}
              {balance?.blockmindToken && (
                <div className="bg-gradient-to-br from-gray-800/50 to-gray-900/50 rounded-2xl border border-gray-700 p-6 mb-6">
                  <h3 className="text-lg font-semibold text-white mb-4">Blockmind Token</h3>
                  <div className="space-y-3">
                    <div className="flex justify-between">
                      <span className="text-gray-400">Balance</span>
                      <span className="text-white font-medium">
                        {balance.blockmindToken.balance.toFixed(2)} BLOCKMIND
                      </span>
                    </div>
                    <div className="flex justify-between">
                      <span className="text-gray-400">SOL Equivalent</span>
                      <span className="text-white font-medium">
                        {balance.blockmindToken.solEquivalent.toFixed(4)} SOL
                      </span>
                    </div>
                    <div className="flex justify-between">
                      <span className="text-gray-400">Discount Eligible</span>
                      <span className={balance.blockmindToken.eligible ? "text-green-400" : "text-gray-500"}>
                        {balance.blockmindToken.eligible ? "✓ Yes" : "✗ No"}
                      </span>
                    </div>
                    {!balance.blockmindToken.eligible && (
                      <p className="text-sm text-gray-500 mt-2">
                        Hold Blockmind tokens worth 1+ SOL to get 33% discount on projects
                      </p>
                    )}
                  </div>
                </div>
              )}

              {/* Deposit Wallet Display */}
              <div className="bg-gradient-to-br from-gray-800/50 to-gray-900/50 rounded-2xl border border-gray-700 p-6 mb-6">
                <div className="flex items-center justify-between mb-4">
                  <h3 className="text-lg font-semibold text-white">Your Deposit Wallet</h3>
                  {balanceLoading && (
                    <span className="text-cyan-400 text-sm">Loading...</span>
                  )}
                </div>

                {balanceError && (
                  <div className="mb-4 p-3 bg-red-500/10 border border-red-500/30 rounded-lg">
                    <p className="text-red-300 text-sm mb-2">{balanceError}</p>
                    <button
                      onClick={() => fetchBalance()}
                      className="text-red-400 hover:text-red-300 text-sm underline"
                    >
                      Retry
                    </button>
                  </div>
                )}

                {balance?.depositWallet ? (
                  <>
                    <p className="text-gray-400 text-sm mb-4">
                      Send payments to this address. We'll automatically detect SOL, USDC, USDT, or Blockmind token payments.
                    </p>
                    
                    {/* QR Code */}
                    <div className="bg-white p-6 rounded-xl mb-4 flex flex-col items-center justify-center shadow-lg">
                      <QRCodeSVG
                        value={balance.depositWallet}
                        size={200}
                        level="H"
                        includeMargin={true}
                      />
                    </div>
                    
                    {/* Wallet Address */}
                    <div className="mb-4">
                      <label className="block text-gray-400 text-sm mb-2">Your Solana Address</label>
                      <div className="flex items-center gap-2">
                        <code className="flex-1 text-sm bg-gray-800/50 p-3 rounded-lg break-all font-mono text-gray-300 border border-gray-700">
                          {balance.depositWallet}
                        </code>
                        <button
                          onClick={() => {
                            navigator.clipboard.writeText(balance.depositWallet);
                            setCopied(true);
                            setTimeout(() => setCopied(false), 2000);
                          }}
                          className="px-4 py-3 bg-cyan-500/20 hover:bg-cyan-500/30 border border-cyan-500/30 rounded-lg text-cyan-300 text-sm font-medium transition-colors flex items-center gap-2 min-w-[100px] justify-center"
                        >
                          {copied ? (
                            <>
                              <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                              </svg>
                              Copied!
                            </>
                          ) : (
                            <>
                              <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
                              </svg>
                              Copy
                            </>
                          )}
                        </button>
                      </div>
                    </div>
                  </>
                ) : balanceLoading ? (
                  <div className="text-center py-8">
                    <p className="text-gray-400 text-sm mb-4">
                      Generating your deposit wallet...
                    </p>
                  </div>
                ) : (
                  <div className="text-center py-8">
                    <p className="text-gray-400 text-sm mb-4">
                      Your deposit wallet is being generated automatically.
                    </p>
                    {!balanceError && (
                      <button
                        onClick={() => fetchBalance()}
                        className="mt-2 px-4 py-2 bg-cyan-500/20 hover:bg-cyan-500/30 border border-cyan-500/30 rounded-lg text-cyan-300 text-sm"
                      >
                        Refresh
                      </button>
                    )}
                  </div>
                )}
              </div>

              {/* Payment Options */}
              {balance && !balance.canCreateFreeProject && (
                <div className="bg-gradient-to-br from-gray-800/50 to-gray-900/50 rounded-2xl border border-gray-700 p-6">
                  <h3 className="text-lg font-semibold text-white mb-4">Pay for Project</h3>
                  <p className="text-gray-400 text-sm mb-4">
                    Pay ${balance.nextProjectPrice.usd.toFixed(2)} USD worth of crypto to create your next project.
                    Send SOL, USDC, USDT, or Blockmind token to your deposit wallet above.
                  </p>

                  <div className="grid grid-cols-2 gap-3 mb-4">
                    {["SOL", "USDC", "USDT", "BLOCKMIND"].map((token) => (
                      <button
                        key={token}
                        onClick={() => handleCreatePaymentIntent(token)}
                        disabled={loading}
                        className="px-4 py-3 bg-gray-800 hover:bg-gray-700 rounded-lg text-white font-medium transition-colors disabled:opacity-50"
                      >
                        Pay with {token}
                      </button>
                    ))}
                  </div>

                  {paymentIntent && (
                    <div className="mt-4 p-4 bg-cyan-500/10 border border-cyan-500/30 rounded-lg">
                      <p className="text-cyan-300 text-sm mb-2">Payment Intent Created</p>
                      <p className="text-cyan-300 text-sm mb-2">
                        Amount: {paymentIntent.amountToken || paymentIntent.amountSol} {paymentIntent.tokenSymbol}
                      </p>
                      <p className="text-gray-400 text-xs mb-2">
                        Send the payment to your deposit wallet above. We'll automatically detect it via webhook.
                      </p>
                      <a
                        href={paymentIntent.solanaPayUrl}
                        className="text-cyan-400 hover:text-cyan-300 text-sm underline"
                      >
                        Open in Solana Pay
                      </a>
                    </div>
                  )}
                </div>
              )}

              {/* Project Count */}
              <div className="mt-6 text-sm text-gray-400">
                <p>Projects created: {balance?.projectCount || 0}</p>
                {balance?.hasFreeProject && (
                  <p className="mt-1">✓ Free project used</p>
                )}
              </div>
            </div>
          )}

          {activeTab === "wallet" && (
            <div className="max-w-3xl">
              <h1 className="text-3xl font-bold text-white mb-2">Wallet</h1>
              <p className="text-gray-400 mb-8">
                Manage your Solana wallet
              </p>

              {/* User Wallet */}
              <div className="bg-gradient-to-br from-gray-800/50 to-gray-900/50 rounded-2xl border border-gray-700 p-6 mb-6">
                <div className="flex items-center justify-between mb-4">
                  <h3 className="text-lg font-semibold text-white">Your Wallet</h3>
                  <div className="flex gap-2">
                    {privyUser?.wallet?.address && (
                      <button
                        onClick={handleExportUserWallet}
                        disabled={exporting}
                        className="px-3 py-1.5 bg-cyan-500/20 hover:bg-cyan-500/30 border border-cyan-500/30 rounded-lg text-cyan-300 text-sm disabled:opacity-50"
                      >
                        {exporting ? 'Exporting...' : 'Export Private Key'}
                      </button>
                    )}
                    <button
                      onClick={() => {
                        setShowImportWallet(true);
                        setShowExportWallet(false);
                        setExportedKey(null);
                      }}
                      className="px-3 py-1.5 bg-gray-700 hover:bg-gray-600 rounded-lg text-gray-300 text-sm"
                    >
                      Import Wallet
                    </button>
                  </div>
                </div>

                {showImportWallet ? (
                  <div className="space-y-4">
                    <div>
                      <label className="block text-gray-400 text-sm mb-2">
                        Private Key (Base58 or JSON array)
                      </label>
                      <textarea
                        value={privateKey}
                        onChange={(e) => {
                          setPrivateKey(e.target.value);
                          setImportError(null);
                        }}
                        placeholder="Enter your private key..."
                        className="w-full px-4 py-3 bg-gray-800 border border-gray-700 rounded-lg text-white font-mono text-sm placeholder-gray-500 focus:outline-none focus:border-cyan-500"
                        rows={4}
                      />
                      <p className="text-gray-500 text-xs mt-2">
                        ⚠️ Your private key is encrypted and stored securely. Only you can access it.
                      </p>
                    </div>

                    {importError && (
                      <div className="p-3 bg-red-500/10 border border-red-500/30 rounded-lg">
                        <p className="text-red-300 text-sm">{importError}</p>
                      </div>
                    )}

                    <div className="flex gap-3">
                      <button
                        onClick={handleImportUserWallet}
                        disabled={importing || !privateKey.trim()}
                        className="px-4 py-2 bg-cyan-500 hover:bg-cyan-600 rounded-lg text-white font-medium transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                      >
                        {importing ? 'Importing...' : 'Import Wallet'}
                      </button>
                      <button
                        onClick={() => {
                          setShowImportWallet(false);
                          setPrivateKey("");
                          setImportError(null);
                        }}
                        className="px-4 py-2 bg-gray-700 hover:bg-gray-600 rounded-lg text-gray-300 font-medium transition-colors"
                      >
                        Cancel
                      </button>
                    </div>
                  </div>
                ) : showExportWallet && exportedKey ? (
                  <div className="space-y-4">
                    <div className="p-4 bg-yellow-500/10 border border-yellow-500/30 rounded-lg">
                      <p className="text-yellow-300 text-sm mb-2">
                        ⚠️ Keep your private key secure! Anyone with access to it can control your wallet.
                      </p>
                    </div>
                    <div>
                      <label className="block text-gray-400 text-sm mb-2">Wallet Address</label>
                      <code className="block w-full px-4 py-2 bg-gray-800 border border-gray-700 rounded-lg text-white font-mono text-sm break-all">
                        {exportedKey.walletAddress}
                      </code>
                    </div>
                    <div>
                      <label className="block text-gray-400 text-sm mb-2">Private Key (Base58)</label>
                      <code className="block w-full px-4 py-2 bg-gray-800 border border-gray-700 rounded-lg text-white font-mono text-sm break-all">
                        {exportedKey.privateKey.base58}
                      </code>
                      <button
                        onClick={() => {
                          navigator.clipboard.writeText(exportedKey.privateKey.base58);
                          alert('Private key copied to clipboard!');
                        }}
                        className="mt-2 px-3 py-1.5 bg-cyan-500/20 hover:bg-cyan-500/30 border border-cyan-500/30 rounded-lg text-cyan-300 text-sm"
                      >
                        Copy Base58
                      </button>
                    </div>
                    <button
                      onClick={() => {
                        setShowExportWallet(false);
                        setExportedKey(null);
                      }}
                      className="w-full px-4 py-2 bg-gray-700 hover:bg-gray-600 rounded-lg text-gray-300 font-medium transition-colors"
                    >
                      Close
                    </button>
                  </div>
                ) : (
                  <div className="space-y-4">
                    {privyUser?.wallet?.address ? (
                      <>
                        <div className="flex justify-between items-center">
                          <span className="text-gray-400">Address</span>
                          <code className="text-white font-mono text-sm">
                            {privyUser.wallet.address}
                          </code>
                        </div>
                        <div className="flex justify-between items-center">
                          <span className="text-gray-400">Provider</span>
                          <span className="text-white">
                            {privyUser.wallet.walletClientType || "privy"}
                          </span>
                        </div>
                        <p className="text-gray-500 text-sm mt-4">
                          This is your connected wallet. You can import a different wallet using your private key, or export the current wallet's private key if it's app-generated.
                        </p>
                      </>
                    ) : (
                      <div className="space-y-4">
                        <p className="text-gray-400 text-sm">
                          Import your Solana wallet using your private key to use it with this account.
                        </p>
                      </div>
                    )}
                  </div>
                )}
              </div>
            </div>
          )}

          {activeTab === "account" && (
            <div className="max-w-3xl">
              <h1 className="text-3xl font-bold text-white mb-2">Account</h1>
              <p className="text-gray-400 mb-8">
                Manage your account settings
              </p>

              <div className="bg-gradient-to-br from-gray-800/50 to-gray-900/50 rounded-2xl border border-gray-700 p-6">
                <h3 className="text-lg font-semibold text-white mb-4">Profile</h3>
                <div className="space-y-4">
                  <div>
                    <label className="block text-gray-400 text-sm mb-2">Email</label>
                    <input
                      type="email"
                      value={privyUser?.email?.address || ""}
                      disabled
                      className="w-full px-4 py-2 bg-gray-800 border border-gray-700 rounded-lg text-white disabled:opacity-50"
                    />
                  </div>
                  <div>
                    <label className="block text-gray-400 text-sm mb-2">User ID</label>
                    <input
                      type="text"
                      value={privyUser?.id || ""}
                      disabled
                      className="w-full px-4 py-2 bg-gray-800 border border-gray-700 rounded-lg text-white disabled:opacity-50 font-mono text-sm"
                    />
                  </div>
                </div>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

